// Generated by CoffeeScript 2.0.0-beta3
(function() {
  module.exports = {
    new: function() {
      return {
        items: [],
        scan: function(x) {
          this.items.push(x);
          return this;
        },
        bogof: function() {
          var count_offer_items, discount;
          count_offer_items = this.items.filter(function(x) {
            return x.code === 'MOH';
          }).length;
          return discount = -169 * Math.floor(count_offer_items / 2);
        },
        total: function() {
          var sum;
          this.items.push({
            code: 'BOGOF',
            price: this.bogof()
          });
          sum = function(acc, x) {
            return acc + x.price;
          };
          return this.items.reduce(sum, 0);
        }
      };
    }
  };

}).call(this);
