// Generated by CoffeeScript 2.0.0-beta3
(function() {
  module.exports = {
    new: function() {
      return {
        items: [],
        scan: function(x) {
          this.items.push(x);
          return this;
        },
        count: function(c) {
          return this.items.filter(function(x) {
            return x.code === c;
          }).length;
        },
        bogof: function() {
          var count, discount;
          count = this.count('MOH');
          return discount = -169 * Math.floor(count / 2);
        },
        bulk_discount: function() {
          var count;
          count = this.count('EQE');
          if (count >= 3) {
            return -50 * count;
          } else {
            return 0;
          }
        },
        total: function() {
          var sum;
          this.items.push({
            code: 'BOGOF',
            price: this.bogof()
          });
          this.items.push({
            code: 'BULK',
            price: this.bulk_discount()
          });
          sum = function(acc, x) {
            return acc + x.price;
          };
          return this.items.reduce(sum, 0);
        }
      };
    }
  };

}).call(this);
